source 'https://rubygems.org'

gem 'commonjs' 
gem 'libv8' 
gem 'therubyracer'
gem 'handlebars' 
gem 'multi_json' 
gem 'multi_xml' 
gem 'httparty' 
gem 'jsmin' 
gem 'tilt'
gem 'sinatra' 
gem 'sinatra-assetpack', :require => 'sinatra/assetpack' 
gem 'pry'
gem 'rspec'
gem 'sass'
gem 'coffee-script'
gem 'debugger', '~> 1.1.3'